import { LOGO_BASE64 } from './logoBase64';

export async function createReportCanvas(transactions, title, formattedDate) {
  let totalDonations = 0;
  let totalExpenses = 0;

  transactions.forEach((tx) => {
    const isDonation = tx.type === 'Donation' || tx.type === 'Donations' || Boolean(tx.donorName);
    const amt = Number(tx.amount || 0);
    if (isDonation) totalDonations += amt;
    else totalExpenses += amt;
  });

  const netBalance = totalDonations - totalExpenses;

  // Scale for ultra-crisp Retina HD output
  const scale = 2;
  const baseWidth = 800;
  const rowHeight = 36;
  const headerHeight = 140;
  const cardsHeight = 90;
  const tableHeaderHeight = 40;
  const tableBodyHeight = Math.max(1, transactions.length) * rowHeight;
  const footerHeight = 70;
  const baseHeight = headerHeight + cardsHeight + tableHeaderHeight + tableBodyHeight + footerHeight + 40;

  const canvas = document.createElement('canvas');
  canvas.width = baseWidth * scale;
  canvas.height = baseHeight * scale;

  const ctx = canvas.getContext('2d');
  ctx.scale(scale, scale);

  // Background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, baseWidth, baseHeight);

  // Top Blue Accent Bar
  ctx.fillStyle = '#0f52ba';
  ctx.fillRect(0, 0, baseWidth, 6);

  // Load and Draw Logo (Top Right)
  try {
    const img = new Image();
    img.src = LOGO_BASE64;
    await new Promise((resolve) => {
      if (img.complete) resolve();
      else {
        img.onload = () => resolve();
        img.onerror = () => resolve();
      }
    });
    ctx.drawImage(img, baseWidth - 110, 20, 80, 80);
  } catch (e) {
    console.warn('Logo draw skipped', e);
  }

  // Header Title & Subtitle
  ctx.fillStyle = '#0f172a';
  ctx.font = 'bold 22px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('Penumuli Perantalamma Youth Tracker', 30, 48);

  ctx.fillStyle = '#0f52ba';
  ctx.font = 'bold 15px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`${title} Report`, 30, 72);

  ctx.fillStyle = '#64748b';
  ctx.font = '500 12px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`Generated Date: ${formattedDate}`, 30, 94);
  ctx.fillText('Generated By: Executive Committee Admin', 30, 112);

  // Header Divider
  ctx.strokeStyle = '#e2e8f0';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(30, 130);
  ctx.lineTo(baseWidth - 30, 130);
  ctx.stroke();

  // Summary Cards
  const cardY = 145;
  const cardWidth = (baseWidth - 60 - 24) / 3; // ~232px
  const cardH = 75;

  // Helper for rounded rectangle
  const drawRoundedRect = (x, y, w, h, radius, fill, stroke) => {
    ctx.beginPath();
    ctx.moveTo(x + radius, y);
    ctx.lineTo(x + w - radius, y);
    ctx.quadraticCurveTo(x + w, y, x + w, y + radius);
    ctx.lineTo(x + w, y + h - radius);
    ctx.quadraticCurveTo(x + w, y + h, x + w - radius, y + h);
    ctx.lineTo(x + radius, y + h);
    ctx.quadraticCurveTo(x, y + h, x, y + h - radius);
    ctx.lineTo(x, y + radius);
    ctx.quadraticCurveTo(x, y, x + radius, y);
    ctx.closePath();
    ctx.fillStyle = fill;
    ctx.fill();
    ctx.strokeStyle = stroke;
    ctx.lineWidth = 1;
    ctx.stroke();
  };

  // Card 1: Total Donations
  drawRoundedRect(30, cardY, cardWidth, cardH, 12, '#ecfdf5', '#a7f3d0');
  ctx.fillStyle = '#065f46';
  ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.textAlign = 'center';
  ctx.fillText('TOTAL DONATIONS', 30 + cardWidth / 2, cardY + 28);
  ctx.fillStyle = '#047857';
  ctx.font = 'bold 18px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`₹${totalDonations.toLocaleString('en-IN')}`, 30 + cardWidth / 2, cardY + 54);

  // Card 2: Total Expenses
  const card2X = 30 + cardWidth + 12;
  drawRoundedRect(card2X, cardY, cardWidth, cardH, 12, '#fff1f2', '#fecdd3');
  ctx.fillStyle = '#9f1239';
  ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('TOTAL EXPENSES', card2X + cardWidth / 2, cardY + 28);
  ctx.fillStyle = '#e11d48';
  ctx.font = 'bold 18px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`₹${totalExpenses.toLocaleString('en-IN')}`, card2X + cardWidth / 2, cardY + 54);

  // Card 3: Net Balance
  const card3X = card2X + cardWidth + 12;
  drawRoundedRect(card3X, cardY, cardWidth, cardH, 12, '#eff6ff', '#bfdbfe');
  ctx.fillStyle = '#1e40af';
  ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('NET BALANCE', card3X + cardWidth / 2, cardY + 28);
  ctx.fillStyle = '#1d4ed8';
  ctx.font = 'bold 18px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`₹${netBalance.toLocaleString('en-IN')}`, card3X + cardWidth / 2, cardY + 54);

  // Reset text align
  ctx.textAlign = 'left';

  // Table Title
  const tableStartY = 245;
  ctx.fillStyle = '#0f172a';
  ctx.font = 'bold 13px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`TRANSACTION AUDIT RECORDS (${transactions.length} ENTRIES)`, 30, tableStartY);

  // Table Header
  const thY = tableStartY + 10;
  ctx.fillStyle = '#f1f5f9';
  ctx.fillRect(30, thY, baseWidth - 60, 32);

  ctx.strokeStyle = '#e2e8f0';
  ctx.strokeRect(30, thY, baseWidth - 60, 32);

  ctx.fillStyle = '#334155';
  ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('#', 42, thY + 20);
  ctx.fillText('Date & Time', 75, thY + 20);
  ctx.fillText('Category / Entry', 200, thY + 20);
  ctx.fillText('Member / Donor', 410, thY + 20);
  ctx.fillText('Mode', 590, thY + 20);
  ctx.textAlign = 'right';
  ctx.fillText('Amount (₹)', baseWidth - 45, thY + 20);
  ctx.textAlign = 'left';

  // Table Rows
  let currentY = thY + 32;

  if (transactions.length === 0) {
    ctx.fillStyle = '#94a3b8';
    ctx.font = '500 12px "Plus Jakarta Sans", sans-serif, Arial';
    ctx.textAlign = 'center';
    ctx.fillText('No transaction records found.', baseWidth / 2, currentY + 24);
    ctx.textAlign = 'left';
    currentY += 40;
  } else {
    transactions.forEach((tx, idx) => {
      const isDonation = tx.type === 'Donation' || tx.type === 'Donations' || Boolean(tx.donorName);
      const amt = Number(tx.amount || 0);
      const txDate = tx.timestamp
        ? new Date(tx.timestamp).toLocaleDateString('en-IN', {
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          })
        : '-';

      const catName = isDonation ? `Donation (${tx.donorName || 'Donor'})` : (tx.category || 'Expense');
      const personName = isDonation ? (tx.donorName || 'Anonymous') : `${tx.memberName || 'Member'} (${tx.memberId || ''})`;
      const mode = tx.paymentMethod || 'Cash';

      // Alternate row background
      if (idx % 2 === 1) {
        ctx.fillStyle = '#f8fafc';
        ctx.fillRect(30, currentY, baseWidth - 60, rowHeight);
      }

      ctx.strokeStyle = '#f1f5f9';
      ctx.strokeRect(30, currentY, baseWidth - 60, rowHeight);

      // Sl No
      ctx.fillStyle = '#94a3b8';
      ctx.font = '500 11px "Plus Jakarta Sans", sans-serif, Arial';
      ctx.fillText(`${idx + 1}`, 42, currentY + 22);

      // Date
      ctx.fillStyle = '#475569';
      ctx.fillText(txDate, 75, currentY + 22);

      // Category
      ctx.fillStyle = '#0f172a';
      ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
      const catTruncated = catName.length > 26 ? catName.substring(0, 24) + '...' : catName;
      ctx.fillText(catTruncated, 200, currentY + 22);

      // Member/Donor
      ctx.fillStyle = '#475569';
      ctx.font = '500 11px "Plus Jakarta Sans", sans-serif, Arial';
      const personTruncated = personName.length > 24 ? personName.substring(0, 22) + '...' : personName;
      ctx.fillText(personTruncated, 410, currentY + 22);

      // Mode Badge
      ctx.fillStyle = '#e2e8f0';
      drawRoundedRect(585, currentY + 8, 48, 20, 4, '#f1f5f9', '#cbd5e1');
      ctx.fillStyle = '#475569';
      ctx.font = 'bold 9px "Plus Jakarta Sans", sans-serif, Arial';
      ctx.textAlign = 'center';
      ctx.fillText(mode.toUpperCase(), 609, currentY + 21);
      ctx.textAlign = 'left';

      // Amount
      ctx.textAlign = 'right';
      ctx.font = 'bold 12px "Plus Jakarta Sans", sans-serif, Arial';
      if (isDonation) {
        ctx.fillStyle = '#059669';
        ctx.fillText(`+ ₹${amt.toLocaleString('en-IN')}`, baseWidth - 45, currentY + 22);
      } else {
        ctx.fillStyle = '#e11d48';
        ctx.fillText(`- ₹${amt.toLocaleString('en-IN')}`, baseWidth - 45, currentY + 22);
      }
      ctx.textAlign = 'left';

      currentY += rowHeight;
    });
  }

  // Footer Divider & Text
  currentY += 15;
  ctx.strokeStyle = '#e2e8f0';
  ctx.beginPath();
  ctx.moveTo(30, currentY);
  ctx.lineTo(baseWidth - 30, currentY);
  ctx.stroke();

  ctx.textAlign = 'center';
  ctx.fillStyle = '#64748b';
  ctx.font = '600 10px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('Official Financial Audit Report · Penumuli Perantalamma Youth Team', baseWidth / 2, currentY + 20);
  ctx.fillStyle = '#94a3b8';
  ctx.font = '400 9px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('Generated automatically via Committee Expenses Tracker System', baseWidth / 2, currentY + 34);

  return canvas;
}
