import { LOGO_BASE64 } from './logoBase64';

export async function createReportCanvas(transactions, title, formattedDate) {
  let totalDonations = 0;
  let totalExpenses = 0;

  const validDateStr = formattedDate || new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  transactions.forEach((tx) => {
    const isDonation = tx.type === 'Donation' || tx.type === 'Donations' || Boolean(tx.donorName);
    const amt = Number(tx.amount || 0);
    if (isDonation) totalDonations += amt;
    else totalExpenses += amt;
  });

  const netBalance = totalDonations - totalExpenses;

  // Scale for ultra-crisp Retina HD output
  const scale = 2;
  const baseWidth = 840;
  const rowHeight = 36;
  const headerHeight = 140;
  const cardsHeight = 90;
  const tableHeaderHeight = 40;
  const tableBodyHeight = Math.max(1, transactions.length) * rowHeight;
  const footerHeight = 70;
  const baseHeight = headerHeight + cardsHeight + tableHeaderHeight + tableBodyHeight + footerHeight + 40;

  const canvas = document.createElement('canvas');
  canvas.width = baseWidth * scale;
  canvas.height = baseHeight * scale;

  const ctx = canvas.getContext('2d');
  ctx.scale(scale, scale);

  // Background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, baseWidth, baseHeight);

  // Top Royal Blue Accent Bar
  ctx.fillStyle = '#0f52ba';
  ctx.fillRect(0, 0, baseWidth, 6);

  // Draw Circular Emblem Logo on Top Right
  const logoCenterX = baseWidth - 75;
  const logoCenterY = 65;
  const logoRadius = 32;

  ctx.beginPath();
  ctx.arc(logoCenterX, logoCenterY, logoRadius, 0, Math.PI * 2);
  ctx.fillStyle = '#eff6ff';
  ctx.fill();
  ctx.strokeStyle = '#bfdbfe';
  ctx.lineWidth = 1.5;
  ctx.stroke();

  try {
    const img = new Image();
    img.src = LOGO_BASE64;
    await new Promise((resolve) => {
      if (img.complete) resolve();
      else {
        img.onload = () => resolve();
        img.onerror = () => resolve();
      }
    });
    ctx.drawImage(img, logoCenterX - 22, logoCenterY - 22, 44, 44);
  } catch (e) {
    console.warn('Logo draw skipped', e);
  }

  // Header Title & Subtitle
  ctx.fillStyle = '#0f172a';
  ctx.font = 'bold 22px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('Penumuli Perantalamma Youth Tracker', 30, 48);

  ctx.fillStyle = '#0f52ba';
  ctx.font = 'bold 15px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`${title} Report`, 30, 72);

  ctx.fillStyle = '#64748b';
  ctx.font = '500 12px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`Generated Date: ${validDateStr}`, 30, 94);
  ctx.fillText('Generated By: Executive Committee Admin', 30, 112);

  // Header Divider
  ctx.strokeStyle = '#e2e8f0';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(30, 130);
  ctx.lineTo(baseWidth - 30, 130);
  ctx.stroke();

  // Summary Cards
  const cardY = 145;
  const cardWidth = (baseWidth - 60 - 24) / 3;
  const cardH = 75;

  const drawRoundedRect = (x, y, w, h, radius, fill, stroke) => {
    ctx.beginPath();
    ctx.moveTo(x + radius, y);
    ctx.lineTo(x + w - radius, y);
    ctx.quadraticCurveTo(x + w, y, x + w, y + radius);
    ctx.lineTo(x + w, y + h - radius);
    ctx.quadraticCurveTo(x + w, y + h, x + w - radius, y + h);
    ctx.lineTo(x + radius, y + h);
    ctx.quadraticCurveTo(x, y + h, x, y + h - radius);
    ctx.lineTo(x, y + radius);
    ctx.quadraticCurveTo(x, y, x + radius, y);
    ctx.closePath();
    ctx.fillStyle = fill;
    ctx.fill();
    ctx.strokeStyle = stroke;
    ctx.lineWidth = 1;
    ctx.stroke();
  };

  // Card 1: Donations (Green)
  drawRoundedRect(30, cardY, cardWidth, cardH, 8, '#ecfdf5', '#a7f3d0');
  ctx.fillStyle = '#065f46';
  ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('TOTAL DONATIONS', 44, cardY + 26);
  ctx.fillStyle = '#047857';
  ctx.font = 'bold 18px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`+ ₹${totalDonations.toLocaleString('en-IN')}`, 44, cardY + 54);

  // Card 2: Expenses (Rose/Amber)
  const card2X = 30 + cardWidth + 12;
  drawRoundedRect(card2X, cardY, cardWidth, cardH, 8, '#fff1f2', '#fecdd3');
  ctx.fillStyle = '#9f1239';
  ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('TOTAL EXPENSES', card2X + 14, cardY + 26);
  ctx.fillStyle = '#e11d48';
  ctx.font = 'bold 18px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`- ₹${totalExpenses.toLocaleString('en-IN')}`, card2X + 14, cardY + 54);

  // Card 3: Net Balance (Blue)
  const card3X = card2X + cardWidth + 12;
  drawRoundedRect(card3X, cardY, cardWidth, cardH, 8, '#eff6ff', '#bfdbfe');
  ctx.fillStyle = '#1e40af';
  ctx.font = 'bold 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('NET BALANCE', card3X + 14, cardY + 26);
  ctx.fillStyle = '#0f52ba';
  ctx.font = 'bold 18px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText(`₹${netBalance.toLocaleString('en-IN')}`, card3X + 14, cardY + 54);

  // Table Header
  const tableStartY = cardY + cardH + 20;
  ctx.fillStyle = '#f1f5f9';
  ctx.fillRect(30, tableStartY, baseWidth - 60, tableHeaderHeight);
  ctx.strokeStyle = '#cbd5e1';
  ctx.strokeRect(30, tableStartY, baseWidth - 60, tableHeaderHeight);

  ctx.fillStyle = '#0f172a';
  ctx.font = 'bold 12px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('Date', 45, tableStartY + 24);
  ctx.fillText('Category / Donor', 160, tableStartY + 24);
  ctx.fillText('Member / Note', 380, tableStartY + 24);
  ctx.fillText('Payment Method', 580, tableStartY + 24);
  ctx.textAlign = 'right';
  ctx.fillText('Amount', baseWidth - 45, tableStartY + 24);
  ctx.textAlign = 'left';

  // Table Rows
  let curY = tableStartY + tableHeaderHeight;
  transactions.forEach((tx, idx) => {
    const isDonation = tx.type === 'Donation' || tx.type === 'Donations' || Boolean(tx.donorName);
    const amt = Number(tx.amount || 0);

    // Row zebra striping
    if (idx % 2 === 1) {
      ctx.fillStyle = '#f8fafc';
      ctx.fillRect(30, curY, baseWidth - 60, rowHeight);
    }

    // Row bottom border
    ctx.strokeStyle = '#f1f5f9';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(30, curY + rowHeight);
    ctx.lineTo(baseWidth - 30, curY + rowHeight);
    ctx.stroke();

    const txDate = tx.timestamp ? new Date(tx.timestamp) : new Date();
    const dateStr = txDate.toLocaleDateString('en-IN', { day: '2-digit', month: 'short' });

    const catStr = isDonation
      ? `Donation (${tx.donorName || tx.name || 'Anonymous'})`
      : (tx.category || 'Expense');

    const memberStr = isDonation
      ? 'Central Donation'
      : (tx.memberName ? `${tx.memberName}` : (tx.note || '-'));

    const methodStr = tx.paymentMethod || 'Cash';

    ctx.fillStyle = '#334155';
    ctx.font = '500 11.5px "Plus Jakarta Sans", sans-serif, Arial';
    ctx.fillText(dateStr, 45, curY + 22);

    // Truncate Category
    ctx.font = '600 11.5px "Plus Jakarta Sans", sans-serif, Arial';
    ctx.fillStyle = '#0f172a';
    const cleanCat = catStr.length > 28 ? catStr.substring(0, 26) + '...' : catStr;
    ctx.fillText(cleanCat, 160, curY + 22);

    // Truncate Note/Member
    ctx.font = '500 11.5px "Plus Jakarta Sans", sans-serif, Arial';
    ctx.fillStyle = '#64748b';
    const cleanMem = memberStr.length > 24 ? memberStr.substring(0, 22) + '...' : memberStr;
    ctx.fillText(cleanMem, 380, curY + 22);

    // Method
    ctx.fillStyle = '#475569';
    ctx.fillText(methodStr, 580, curY + 22);

    // Amount: Green for donation, Red for expense
    ctx.font = 'bold 12.5px "Plus Jakarta Sans", sans-serif, Arial';
    ctx.textAlign = 'right';
    if (isDonation) {
      ctx.fillStyle = '#047857';
      ctx.fillText(`+ ₹${amt.toLocaleString('en-IN')}`, baseWidth - 45, curY + 22);
    } else {
      ctx.fillStyle = '#e11d48';
      ctx.fillText(`- ₹${amt.toLocaleString('en-IN')}`, baseWidth - 45, curY + 22);
    }
    ctx.textAlign = 'left';

    curY += rowHeight;
  });

  // Footer Divider & Text
  const footY = curY + 25;
  ctx.strokeStyle = '#e2e8f0';
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(30, footY);
  ctx.lineTo(baseWidth - 30, footY);
  ctx.stroke();

  ctx.fillStyle = '#64748b';
  ctx.font = '600 11px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('Penumuli Youth Committee · Authorized Financial Audit Report', 30, footY + 22);

  ctx.textAlign = 'right';
  ctx.fillStyle = '#94a3b8';
  ctx.font = '500 10px "Plus Jakarta Sans", sans-serif, Arial';
  ctx.fillText('PR Youth Expenses Tracker System', baseWidth - 30, footY + 22);
  ctx.textAlign = 'left';

  return canvas;
}
